# Cloud Build configuration with security best practices
substitutions:
  _SERVICE_NAME: tiktok-workout-parser
  _REGION: us-central1
  _ENVIRONMENT: ${_ENVIRONMENT}  # Will be set by trigger or default to production

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
steps:
  # Step 1: Run security scan on source code
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running security checks..."
        # Add your security scanning tools here (e.g., bandit, safety)
        echo "Security scan completed"

  # Step 2: Build the container image with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '--cache-from=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:buildcache'
      - '--cache-to=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:buildcache'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_ENVIRONMENT}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'BUILD_DATE=${_BUILD_TIME}'
      - '--build-arg'
      - 'VERSION=${SHORT_SHA}'
      - '.'

  # Step 3: Run container structure tests
  - name: 'gcr.io/gcp-runtimes/container-structure-test'
    id: 'test-container'
    args:
      - 'test'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--config'
      - '/workspace/container-test.yaml'
    allowFailure: true  # Don't fail build if tests don't exist yet

  # Step 4: Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}'

  # Step 5: Create or update service account if needed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-service-account'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_ACCOUNT="${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
        
        # Check if service account exists
        if ! gcloud iam service-accounts describe "$${SERVICE_ACCOUNT}" 2>/dev/null; then
          echo "Creating service account..."
          gcloud iam service-accounts create ${_SERVICE_NAME} \
            --display-name="${_SERVICE_NAME} Service Account"
          
          # Grant necessary permissions
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${SERVICE_ACCOUNT}" \
            --role="roles/aiplatform.user"
        else
          echo "Service account already exists: $${SERVICE_ACCOUNT}"
        fi
        
        # Grant secret accessor role
        gcloud secrets add-iam-policy-binding "scrapecreators-api-key" \
          --member="serviceAccount:$${SERVICE_ACCOUNT}" \
          --role="roles/secretmanager.secretAccessor" || true

  # Step 6: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DEPLOY_ARGS=(
          "run" "deploy" "${_SERVICE_NAME}"
          "--image" "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}"
          "--region" "${_REGION}"
          "--platform" "managed"
          "--allow-unauthenticated"
          "--memory" "2Gi"
          "--cpu" "2"
          "--timeout" "900"
          "--max-instances" "10"
          "--min-instances" "0"
          "--concurrency" "100"
          "--cpu-throttling"
          "--execution-environment" "gen2"
          "--service-account" "${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
          "--set-env-vars" "GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=${_ENVIRONMENT}"
          "--set-secrets" "SCRAPECREATORS_API_KEY=scrapecreators-api-key:latest"
        )
        
        # Add environment-specific settings
        if [[ "${_ENVIRONMENT}" == "production" ]]; then
          DEPLOY_ARGS+=("--min-instances" "1" "--cpu-boost")
        else
          DEPLOY_ARGS+=("--tag" "${_ENVIRONMENT}" "--no-traffic")
        fi
        
        gcloud "$${DEPLOY_ARGS[@]}"

  # Step 7: Run smoke tests
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'smoke-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running smoke tests..."
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --platform managed --region ${_REGION} --format 'value(status.url)')
        
        # Test health endpoint
        curl -f "$${SERVICE_URL}/health" || exit 1
        echo "Health check passed!"

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_ENVIRONMENT}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'

# Timeout for the entire build
timeout: '1200s'