# Cloud Build configuration with security best practices
substitutions:
  _SERVICE_NAME: workout-parser
  _REGION: us-central1
  _ENVIRONMENT: production

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
steps:
  # Step 1: Run security scan on source code
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running security checks..."
        # Add your security scanning tools here (e.g., bandit, safety)
        echo "Security scan completed"

  # Step 2: Build the container image with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '--cache-from=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:buildcache'
      - '--cache-to=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:buildcache'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_ENVIRONMENT}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)'
      - '--build-arg'
      - 'VERSION=${SHORT_SHA}'
      - '.'

  # Step 3: Run container structure tests
  - name: 'gcr.io/gcp-runtimes/container-structure-test'
    id: 'test-container'
    args:
      - 'test'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--config'
      - '/workspace/container-test.yaml'
    allowFailure: true  # Don't fail build if tests don't exist yet

  # Step 4: Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}'

  # Step 5: Create or update service account if needed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-service-account'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_ACCOUNT="${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
        
        # Check if service account exists
        if ! gcloud iam service-accounts describe "$${SERVICE_ACCOUNT}" 2>/dev/null; then
          echo "Creating service account..."
          gcloud iam service-accounts create ${_SERVICE_NAME} \
            --display-name="${_SERVICE_NAME} Service Account"
          
          # Grant necessary permissions
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${SERVICE_ACCOUNT}" \
            --role="roles/aiplatform.user"
        else
          echo "Service account already exists: $${SERVICE_ACCOUNT}"
        fi
        
        # Grant secret accessor role
        gcloud secrets add-iam-policy-binding "scrapecreators-api-key" \
          --member="serviceAccount:$${SERVICE_ACCOUNT}" \
          --role="roles/secretmanager.secretAccessor" || true

  # Step 6: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DEPLOY_ARGS=(
          "run" "deploy" "${_SERVICE_NAME}"
          "--image" "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}"
          "--region" "${_REGION}"
          "--platform" "managed"
          "--allow-unauthenticated"
          "--memory" "2Gi"
          "--cpu" "2"
          "--timeout" "900"
          "--max-instances" "50"
          "--min-instances" "0"
          "--concurrency" "80"
          "--cpu-throttling"
          "--execution-environment" "gen2"
          "--service-account" "${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
          "--set-env-vars" "GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=${_ENVIRONMENT},MAX_CONCURRENT_PROCESSING=40,RATE_LIMIT_REQUESTS=20,RATE_LIMIT_WINDOW=60"
          "--set-secrets" "SCRAPECREATORS_API_KEY=scrapecreators-api-key:latest"
        )
        
        # Add environment-specific settings
        if [[ "${_ENVIRONMENT}" == "production" ]]; then
          DEPLOY_ARGS+=("--min-instances" "1" "--cpu-boost")
        else
          DEPLOY_ARGS+=("--tag" "${_ENVIRONMENT}" "--no-traffic")
        fi
        
        gcloud "$${DEPLOY_ARGS[@]}"

  # Step 7: Deploy worker service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-worker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying worker service..."
        
        # Create worker service account if needed
        WORKER_SA="workout-parser-worker@${PROJECT_ID}.iam.gserviceaccount.com"
        if ! gcloud iam service-accounts describe "$${WORKER_SA}" 2>/dev/null; then
          echo "Creating worker service account..."
          gcloud iam service-accounts create workout-parser-worker \
            --display-name="TikTok Workout Worker Service Account"
          
          # Grant necessary permissions
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${WORKER_SA}" \
            --role="roles/datastore.user"
          
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${WORKER_SA}" \
            --role="roles/aiplatform.user"
        fi
        
        # Deploy worker service
        gcloud run deploy workout-parser-worker \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --timeout 300 \
          --concurrency 1 \
          --max-instances 10 \
          --min-instances 1 \
          --port 8081 \
          --command python \
          --args -m,src.worker.worker_service \
          --set-env-vars GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=${_ENVIRONMENT} \
          --set-secrets SCRAPECREATORS_API_KEY=scrapecreators-api-key:latest \
          --service-account "$${WORKER_SA}"

  # Step 8: Validate deployment health
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Validating deployment health..."
        
        # Get service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --platform managed --region ${_REGION} --format 'value(status.url)')
        
        # Wait for service to be ready (max 5 minutes)
        for i in {1..30}; do
          echo "Health check attempt $i/30..."
          
          if curl -f -s --max-time 10 "$${SERVICE_URL}/health" > /dev/null; then
            echo "✅ Health check passed!"
            break
          fi
          
          if [ $i -eq 30 ]; then
            echo "❌ Health check failed after 5 minutes"
            echo "Rolling back deployment..."
            
            # Get previous revision
            PREVIOUS_REVISION=$(gcloud run revisions list \
              --service=${_SERVICE_NAME} --region=${_REGION} \
              --format='value(metadata.name)' --limit=2 | tail -n 1)
            
            if [ ! -z "$PREVIOUS_REVISION" ]; then
              echo "Rolling back to revision: $PREVIOUS_REVISION"
              gcloud run services update-traffic ${_SERVICE_NAME} \
                --to-revisions=$PREVIOUS_REVISION=100 \
                --region=${_REGION}
            fi
            
            exit 1
          fi
          
          sleep 10
        done
        
        # Run comprehensive smoke tests
        echo "Running smoke tests..."
        
        # Test health endpoint with detailed validation
        HEALTH_RESPONSE=$(curl -s "$${SERVICE_URL}/health")
        echo "Health response: $HEALTH_RESPONSE"
        
        # Validate health response structure
        if ! echo "$HEALTH_RESPONSE" | jq -e '.status' > /dev/null; then
          echo "❌ Health endpoint returned invalid JSON"
          exit 1
        fi
        
        HEALTH_STATUS=$(echo "$HEALTH_RESPONSE" | jq -r '.status')
        if [ "$HEALTH_STATUS" != "healthy" ] && [ "$HEALTH_STATUS" != "degraded" ]; then
          echo "❌ Health status is: $HEALTH_STATUS"
          exit 1
        fi
        
        # Test status endpoint
        curl -f "$${SERVICE_URL}/status" | jq .status || {
          echo "❌ Status endpoint failed"
          exit 1
        }
        
        # Test API structure (should return 422 for invalid input, not 500)
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
          -X POST "$${SERVICE_URL}/process" \
          -H "Content-Type: application/json" \
          -d '{"url": "invalid-url"}')
        
        if [ "$HTTP_CODE" != "422" ]; then
          echo "❌ Process endpoint validation failed (expected 422, got $HTTP_CODE)"
          exit 1
        fi
        
        echo "✅ All smoke tests passed!"
        echo "✅ Deployment validation complete!"

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_ENVIRONMENT}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'

# Timeout for the entire build
timeout: '1200s'