# Cloud Build configuration with multi-region deployment and performance optimizations
substitutions:
  _SERVICE_NAME: workout-parser-v2
  _PRIMARY_REGION: us-central1
  _SECONDARY_REGIONS: us-east1,europe-west1,asia-southeast1
  _ENVIRONMENT: production

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
steps:
  # Step 1: Run security scan on source code
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running security checks..."
        # Add your security scanning tools here (e.g., bandit, safety)
        echo "Security scan completed"

  # Step 2: Build the container image with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '--cache-from=${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:buildcache'
      - '--cache-to=${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:buildcache'
      - '-t'
      - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_ENVIRONMENT}'
      - '-t'
      - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)'
      - '--build-arg'
      - 'VERSION=${SHORT_SHA}'
      - '.'

  # Step 3: Run container structure tests
  - name: 'gcr.io/gcp-runtimes/container-structure-test'
    id: 'test-container'
    args:
      - 'test'
      - '--image'
      - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--config'
      - '/workspace/container-test.yaml'
    allowFailure: true  # Don't fail build if tests don't exist yet

  # Step 4: Push images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args:
      - 'push'
      - '--all-tags'
      - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}'

  # Step 5: Create or update service account if needed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-service-account'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_ACCOUNT="${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
        
        # Check if service account exists
        if ! gcloud iam service-accounts describe "$${SERVICE_ACCOUNT}" 2>/dev/null; then
          echo "Creating service account..."
          gcloud iam service-accounts create ${_SERVICE_NAME} \
            --display-name="${_SERVICE_NAME} Service Account"
          
          # Grant necessary permissions
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${SERVICE_ACCOUNT}" \
            --role="roles/aiplatform.user"
        else
          echo "Service account already exists: $${SERVICE_ACCOUNT}"
        fi
        
        # Grant secret accessor role
        gcloud secrets add-iam-policy-binding "scrapecreators-api-key" \
          --member="serviceAccount:$${SERVICE_ACCOUNT}" \
          --role="roles/secretmanager.secretAccessor" || true

  # Step 6: Deploy to Primary Region (us-central1)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-primary'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to primary region: ${_PRIMARY_REGION}"
        
        DEPLOY_ARGS=(
          "run" "deploy" "${_SERVICE_NAME}"
          "--image" "${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}"
          "--region" "${_PRIMARY_REGION}"
          "--platform" "managed"
          "--allow-unauthenticated"
          "--memory" "4Gi"
          "--cpu" "4"
          "--timeout" "900"
          "--max-instances" "100"
          "--min-instances" "2"
          "--concurrency" "100"
          "--cpu-throttling"
          "--execution-environment" "gen2"
          "--service-account" "${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
          "--set-env-vars" "GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=${_ENVIRONMENT},MAX_CONCURRENT_PROCESSING=80,RATE_LIMIT_REQUESTS=50,RATE_LIMIT_WINDOW=60,MAX_DIRECT_PROCESSING=20,GEMINI_REGIONS=${_PRIMARY_REGION},${_SECONDARY_REGIONS},APPCHECK_REQUIRED=true"
          "--set-secrets" "SCRAPECREATORS_API_KEY=scrapecreators-api-key:latest"
        )
        
        # Add environment-specific settings
        if [[ "${_ENVIRONMENT}" == "production" ]]; then
          DEPLOY_ARGS+=("--cpu-boost")
        else
          DEPLOY_ARGS+=("--tag" "${_ENVIRONMENT}" "--no-traffic")
        fi
        
        gcloud "$${DEPLOY_ARGS[@]}"

  # Step 7: Deploy to Secondary Regions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-secondary'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to secondary regions: ${_SECONDARY_REGIONS}"
        
        IFS=',' read -ra REGIONS <<< "${_SECONDARY_REGIONS}"
        for region in "${REGIONS[@]}"; do
          region=$(echo $region | xargs)  # trim whitespace
          echo "Deploying to region: $region"
          
          # Copy image to region's registry if needed
          gcloud artifacts repositories create ${_SERVICE_NAME} \
            --repository-format=docker \
            --location=$region \
            --description="Docker repository for ${_SERVICE_NAME}" || true
          
          # Tag and push image to regional registry
          docker tag ${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA} \
                     $region-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA} || true
          
          docker push $region-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA} || true
          
          # Deploy to region
          gcloud run deploy ${_SERVICE_NAME} \
            --image $region-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA} \
            --region $region \
            --platform managed \
            --allow-unauthenticated \
            --memory 4Gi \
            --cpu 4 \
            --timeout 900 \
            --max-instances 100 \
            --min-instances 1 \
            --concurrency 100 \
            --cpu-throttling \
            --execution-environment gen2 \
            --service-account ${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com \
            --set-env-vars GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=${_ENVIRONMENT},MAX_CONCURRENT_PROCESSING=80,RATE_LIMIT_REQUESTS=50,RATE_LIMIT_WINDOW=60,MAX_DIRECT_PROCESSING=20,GEMINI_REGIONS=${_PRIMARY_REGION},${_SECONDARY_REGIONS},APPCHECK_REQUIRED=true \
            --set-secrets SCRAPECREATORS_API_KEY=scrapecreators-api-key:latest || {
              echo "Failed to deploy to $region, continuing..."
            }
        done

  # Step 8: Deploy worker service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-worker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying worker service..."
        
        # Create worker service account if needed
        WORKER_SA="workout-parser-worker@${PROJECT_ID}.iam.gserviceaccount.com"
        if ! gcloud iam service-accounts describe "$${WORKER_SA}" 2>/dev/null; then
          echo "Creating worker service account..."
          gcloud iam service-accounts create workout-parser-worker \
            --display-name="TikTok Workout Worker Service Account"
          
          # Grant necessary permissions
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${WORKER_SA}" \
            --role="roles/datastore.user"
          
          gcloud projects add-iam-policy-binding ${PROJECT_ID} \
            --member="serviceAccount:$${WORKER_SA}" \
            --role="roles/aiplatform.user"
        fi
        
        # Deploy worker service to primary region
        gcloud run deploy workout-parser-worker \
          --image ${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA} \
          --region ${_PRIMARY_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory 4Gi \
          --cpu 2 \
          --timeout 300 \
          --concurrency 1 \
          --max-instances 20 \
          --min-instances 2 \
          --port 8081 \
          --command python \
          --args -m,src.worker.worker_service \
          --set-env-vars GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=${_ENVIRONMENT},GEMINI_REGIONS=${_PRIMARY_REGION},${_SECONDARY_REGIONS} \
          --set-secrets SCRAPECREATORS_API_KEY=scrapecreators-api-key:latest \
          --service-account "$${WORKER_SA}"

  # Step 9: Setup Global Load Balancer (optional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-load-balancer'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up global load balancer for multi-region deployment..."
        
        # Create global load balancer configuration
        # This step is optional and can be configured separately
        echo "Load balancer setup can be done manually or via Terraform"
        echo "Primary region: ${_PRIMARY_REGION}"
        echo "Secondary regions: ${_SECONDARY_REGIONS}"
        
        # For now, just output the service URLs
        echo "=== Service URLs ==="
        echo "Primary: https://${_SERVICE_NAME}-$(echo ${PROJECT_ID} | tr ':' '-')-uc.a.run.app"
        
        IFS=',' read -ra REGIONS <<< "${_SECONDARY_REGIONS}"
        for region in "${REGIONS[@]}"; do
          region=$(echo $region | xargs)
          region_code=$(echo $region | cut -d'-' -f1-2 | tr '-' '')
          echo "$region: https://${_SERVICE_NAME}-$(echo ${PROJECT_ID} | tr ':' '-')-${region_code}.a.run.app"
        done

  # Step 10: Validate deployment health
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate-deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Validating deployment health..."
        
        # Get primary service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --platform managed --region ${_PRIMARY_REGION} --format 'value(status.url)')
        
        # Wait for service to be ready (max 5 minutes)
        for i in {1..30}; do
          echo "Health check attempt $i/30..."
          
          if curl -f -s --max-time 10 "$${SERVICE_URL}/health" > /dev/null; then
            echo "✅ Health check passed!"
            break
          fi
          
          if [ $i -eq 30 ]; then
            echo "❌ Health check failed after 5 minutes"
            echo "Rolling back deployment..."
            
            # Get previous revision
            PREVIOUS_REVISION=$$(gcloud run revisions list \
              --service=${_SERVICE_NAME} --region=${_PRIMARY_REGION} \
              --format='value(metadata.name)' --limit=2 | tail -n 1)
            
            if [ ! -z "$$PREVIOUS_REVISION" ]; then
              echo "Rolling back to revision: $$PREVIOUS_REVISION"
              gcloud run services update-traffic ${_SERVICE_NAME} \
                --to-revisions=$$PREVIOUS_REVISION=100 \
                --region=${_PRIMARY_REGION}
            fi
            
            exit 1
          fi
          
          sleep 10
        done
        
        # Run comprehensive smoke tests
        echo "Running smoke tests..."
        
        # Test health endpoint with detailed validation
        HEALTH_RESPONSE=$$(curl -s "$${SERVICE_URL}/health")
        echo "Health response: $$HEALTH_RESPONSE"
        
        # Validate health response structure
        if ! echo "$$HEALTH_RESPONSE" | jq -e '.status' > /dev/null; then
          echo "❌ Health endpoint returned invalid JSON"
          exit 1
        fi
        
        HEALTH_STATUS=$$(echo "$$HEALTH_RESPONSE" | jq -r '.status')
        if [ "$$HEALTH_STATUS" != "healthy" ] && [ "$$HEALTH_STATUS" != "degraded" ]; then
          echo "❌ Health status is: $$HEALTH_STATUS"
          exit 1
        fi
        
        # Test status endpoint
        curl -f "$${SERVICE_URL}/status" | jq .status || {
          echo "❌ Status endpoint failed"
          exit 1
        }
        
        # Test API structure (should return 422 for invalid input, not 500)
        HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" \
          -X POST "$${SERVICE_URL}/process" \
          -H "Content-Type: application/json" \
          -d '{"url": "invalid-url"}')
        
        if [ "$$HTTP_CODE" != "422" ]; then
          echo "❌ Process endpoint validation failed (expected 422, got $$HTTP_CODE)"
          exit 1
        fi
        
        echo "✅ All smoke tests passed!"
        
        # Test regional health endpoint
        curl -f "$${SERVICE_URL}/health/regions" | jq .status || {
          echo "❌ Regional health endpoint failed"
          exit 1
        }
        
        # Test performance metrics endpoint
        curl -f "$${SERVICE_URL}/metrics/performance" | jq .performance_metrics || {
          echo "❌ Performance metrics endpoint failed"
          exit 1
        }
        
        echo "✅ All smoke tests passed!"
        echo "✅ Multi-region deployment validation complete!"

# Store images in Artifact Registry (primary region)
images:
  - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:${_ENVIRONMENT}'
  - '${_PRIMARY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}:latest'

# Timeout for the entire build (increased for multi-region deployment)
timeout: '2400s'